on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours
  workflow_dispatch:         # Allows manual triggering

jobs:
  sync_google_sheets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install  # If using a Gemfile
          gem install icalendar  # Ensure icalendar is installed

      - name: Run Locker Room Monitors Script
        env:
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
          GOOGLE_SHEET_ID_12A: ${{ secrets.GOOGLE_SHEET_ID_12A }}
          GOOGLE_SHEET_ID_12B1: ${{ secrets.GOOGLE_SHEET_ID_12B1 }}
          GOOGLE_SHEET_ID_10B1: ${{ secrets.GOOGLE_SHEET_ID_10B1 }}
          GOOGLE_SHEET_ID_10B2: ${{ secrets.GOOGLE_SHEET_ID_10B2 }}
        run: ruby locker_room_monitor.rb