name: Run Locker Room Monitor Script & Sync Google Sheets
on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours
  workflow_dispatch:         # Allows manual triggering

jobs:
  sync_google_sheets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.201.0
        with:
          ruby-version: '3.1'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install  # If using a Gemfile
          gem install icalendar  # Ensure icalendar is installed

      - name: Run Locker Room Monitors Script
        env:
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
          GOOGLE_SHEET_ID_12A: ${{ secrets.GOOGLE_SHEET_ID_12A }}
          GOOGLE_SHEET_ID_12B1: ${{ secrets.GOOGLE_SHEET_ID_12B1 }}
          GOOGLE_SHEET_ID_10B1: ${{ secrets.GOOGLE_SHEET_ID_10B1 }}
          GOOGLE_SHEET_ID_10B2: ${{ secrets.GOOGLE_SHEET_ID_10B2 }}
        run: ruby locker_room_monitor.rb
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Commit and Push Changes (if any)
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Update CSV and iCal feed"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 