name: Run Locker Room Monitor Script

on:
  # Triggers the workflow on a schedule (cron syntax)
  schedule:
    - cron: "0 0 * * 1"  # Runs every Monday at midnight UTC
  # Trigger the workflow manually
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  # Adjust the Ruby version if needed

      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run Locker Room Monitor Script
        run: |
          ruby locker_room_monitor.rb

      - name: Commit and Push Changes (if any)
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Update CSV and iCal feed"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
